- class: nav-tabs nav-tabs-responsive
  type: tabs
  menu:
  - text: Branch Settings
    url: branch-settings

  - text: Business Hours
    url: business-hours

  - text: Services & Products
    url: services-and-products
